### ISSUE TITLE
cmysql not installing on xcode 12 with swift-tools-version:5.3

### ISSUE THREAD

**Issue by Nevwild** [novi/mysql-swift#103]
When adding mysql-swift as a dependency, cmysql is not being loaded, and MySQL is not available for import. 
<img width="344" alt="Screen Shot 2020-07-13 at 2 05 34 PM" src="https://user-images.githubusercontent.com/11260195/87366775-bc859b80-c536-11ea-9ed0-d5786ee7476b.png">

**Comment by novi** [comment]
We could install cmysql with https://github.com/novi/mysql-swift#macos.

**Comment by Nevwild** [comment]
I got it working. Thank you.
