### ISSUE TITLE
Compile error with swift 2016-01-25 snapshot

### ISSUE THREAD

**Issue by sbuerk** [novi/mysql-swift#11]
Just switched the the swift compiler to the [current delevoper snapshot 2016-01-25](https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2016-01-25-a/swift-DEVELOPMENT-SNAPSHOT-2016-01-25-a-ubuntu14.04.tar.gz), and now my simple playground project with a simple mysql query won't compile anymore.

Build log snippet:

> Compiling Swift Module 'MySQL' (13 sources)
> /var/www/sbuerk/switf/swift-playground-one/Packages/mysql-swift-0.1.5/Sources/Builder.swift:11:28: error: curried function declaration syntax has been removed; use a single parameter list
> public func build<A, Value>(create: (A) -> Value)(_ a: A) -> Value {

It seems it is an issue because of [Removing currying func declaration syntax - Proposal: SE-0002](https://github.com/apple/swift-evolution/blob/master/proposals/0002-remove-currying.md)

I have created a gist with the full log here: [full_build_log](https://gist.github.com/sbuerk/cea0f5d9d878536a6ae1)

Since i'm just playing around with swift on linux (started learning 7 days ago, with ~5h free time playing) i' could not provide an PR for it ... maybe i find some time at the weekend, but don't think so ... to many projects at work at the moment.

Just wanna share that issue ...

If i could provide further informations for that, let me know it.

**Comment by novi** [comment]
Thank you for information.
Actually, Currying func syntax will be removed in further Swift releases.
I did refactoring by removing these syntax from this library and released it as tag `0.1.6` (see #12). Now you can compile it and its demos.
