### ISSUE TITLE
Complie with Xcode failed

### ISSUE THREAD

**Issue by CreatorMetaSky** [novi/mysql-swift#18]
![image](https://cloud.githubusercontent.com/assets/8367760/13807662/2f136af6-eb9d-11e5-8b07-bd6cd0f3477f.png)

I use xcode complie my codes and dependency on your mysql-swift library

the step is :
1. use `carthage update` build the framework, and drag drop to the build phases
2. add framework search path 
3. add the moudle.map path to the import paths in build settings

finally i use your sample code, but when i call `pool.execute` method , it always complie error.

pelease help me, thanks.

**Comment by CreatorMetaSky** [comment]
oh, i have fix it by make it a dylib, i think use carthage is bad for spm

**Comment by novi** [comment]
With SPM, Carthage or Xcode based framework may not work.
Use `Package.swift` and  `swift build` instead.

If you have a problem with Carthage and Xcode, add MySQL.xcodeproj into your project and link MySQL.framework in Build Phase setting of your project.
