### ISSUE TITLE
Carthage issues

### ISSUE THREAD

**Issue by Wachiwi** [novi/mysql-swift#27]
I am a OS X user and have some weird issues installing mysql-swift via carthage. I uploaded the log of the errors to [pastebin[(http://pastebin.com/K3aYiQgN). Do you know a solution to this or could you give me some hints how I can dive into the problem to solve it?

Cartfile:

```
github "novi/mysql-swift" "master"
```

**Comment by novi** [comment]
Thank you for reporting!

mysql-swift supports Swift 3 latest snapshot (currently 05-31-a).
So, you could specify Swift toolchain and run `carthage update` to build it.
(No specifying a toolchain, Carthage uses default toolchain of Xcode, it will be Swift 2.2)

And I have made minor fixes for Carthage and updated README to work with latest toolchain.
