### ISSUE TITLE
Connecting to database

### ISSUE THREAD

**Issue by artur-ios-dev** [novi/mysql-swift#30]
Hello,

I have an error while trying to connect to the database.

`connectionError("Lost connection to MySQL server at \'waiting for initial communication packet\', system error: 60 \"Operation timed out\"")`

What I might be doing wrong? 

Here is my ConnectionOption (I had to hide my addresses etc):

```
struct Options : ConnectionOption {
    let host: String = "xxxxxx"
    let port: Int = xxxx
    let user: String = "username"
    let password: String = "xxxxx"
    let database: String = "xxxxxx"
    let timeout: Int = 10
    let omitDetailsOnError : Bool = false
}
```

and here is how I call the execute:

```
do {
            let status: QueryStatus = try pool.execute { conn in
                try conn.query("SELECT * FROM users;") // And also it returns result to outside execute block
            }
            print(status.description)
        } catch let error {
            print("Error occurred:\n \(error)")
        }
```

**Comment by novi** [comment]
It seems have a problem on a network.
Have you connected with `mysql` command directly?
Is it first trying? or does it occur after some minutes later?
