### ISSUE TITLE
installing with mariadb and swift 3 pre Problem

### ISSUE THREAD

**Issue by jihadfee** [novi/mysql-swift#32]
Having a problem install

root@igentik:/home/ecnxdev/swift/test2# swift build -Xcc -fblocks -Xlinker -ldispatch -L /usr/lib
error: unknown command: -L
enter `/usr/local/swift/usr/bin/swift-build --help' for usage information
root@igentik:/home/ecnxdev/swift/test2# swift build -Xcc -fblocks -Xlinker -ldispatch
note: you may be able to install mariadb using your system-packager:

```
apt-get install libmariadbclient-dev
```

note: you may be able to install mariadb using your system-packager:

```
apt-get install libmariadbclient-dev
```

note: you may be able to install mariadb using your system-packager:

```
apt-get install libmariadbclient-dev
```

note: you may be able to install mariadb using your system-packager:

```
apt-get install libmariadbclient-dev
```

root@igentik:/home/ecnxdev/swift/test2# apt-get install libmariadbclient-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libmariadbclient-dev is already the newest version (5.5.36-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@igentik:/home/ecnxdev/swift/test2# swift
Welcome to Swift version 3.0 (swift-3.0-PREVIEW-2). Type :help for assistance.

**Comment by novi** [comment]
Displaying `note` is normal. You are all set.
Go `swift build` and the build will be done with that.
