### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by ebprupesh** [novi/mysql-swift#33]
Please help,

when using this  command   "swift build -Xlinker -L/usr/local/lib -Xcc -I/usr/local/include -Xcc -I/usr/local/include/mysql"  from terminal the project builds successfully. 

But when building via xcode it gives me error 
_ld: library not found for -lssl_
_clang: error: linker command failed with exit code 1 (use -v to see invocation)_

Sorry found the solution :)

**Comment by ghost** [comment]
If someone else has this problem, I had to add "/usr/local/ssl/lib" to the library seach paths in the project build settings.
