### ISSUE TITLE
Swift 3 warnings, operator precedence deprecation

### ISSUE THREAD

**Issue by popaaaandrei** [novi/mysql-swift#41]
I have fixed some warnings in XCode 8. Would you like me to make a PR? It's not much, just some `@noescape` and unused results.

Another warning is for the deprecated operator declaration.

```
warning: operator should no longer be declared with body; use a precedence group instead
infix operator <| { associativity left precedence 150 }
                  ^
warning: operator should no longer be declared with body; use a precedence group instead
infix operator <|? { associativity left precedence 150 }
                   ^
```

As discussed in [swift-evolution](https://github.com/apple/swift-evolution/blob/master/proposals/0077-operator-precedence.md) a possible fix would be 

```
// Before
infix operator <|  {  associativity left precedence 150 }

// After
precedencegroup ComparisonPrecedence {
  associativity: left
  higherThan: LogicalConjunctionPrecedence
}
infix operator <| : ComparisonPrecedence
```

I don't know what you had in mind when you put 150, but I'm thinking that it should have the precedence around `AdditivePrecedence`.

Andrei

**Comment by novi** [comment]
Thank you @popaaaandrei.
The operator(and 150 of precedence) comes from some other JSON decoding framework that I have referred to. `AdditivePrecedence` looks good.
Could you make a pull request?

**Comment by popaaaandrei** [comment]
https://github.com/novi/mysql-swift/pull/43
