### ISSUE TITLE
Use `pkgConfig` to link mysqlclient.

### ISSUE THREAD

**Issue by PrasannaKumarChalla** [novi/mysql-swift#51]
Can we use SPM's `pkgConfig` option to link mysql client?. By doing this we can get rid of the Xcode project, config files. This may involve adding a .pc file once(if it doesn't already exists.) . So basically making CMySql into something like https://github.com/vapor/cmysql .

**Comment by novi** [comment]
Thanks for a information. We will refactor to use the `pkgConfig` option.
