### ISSUE TITLE
Want to support 4.0

### ISSUE THREAD

**Issue by kuhippo** [novi/mysql-swift#55]

**Comment by kuhippo** [comment]
With the swift mysql name repetition

**Comment by novi** [comment]
I'm working on Swift 4 here. [origin/swift4](https://github.com/novi/mysql-swift/tree/swift4)
It should works.

**Comment by kuhippo** [comment]
If not through swiftpackage installation

**Comment by novi** [comment]
have released `0.8.0`.

**Comment by kuhippo** [comment]
love you
