### ISSUE TITLE
Not compiling with Swift 4

### ISSUE THREAD

**Issue by LinusGeffarth** [novi/mysql-swift#57]
I have imported all the files inside _"Sources"_, into my Xcode project.  
Xcode's giving me multiple errors:

    private var mysql_: UnsafeMutablePointer<MYSQL>? // Use of undeclared type 'MYSQL'

Same for `mysql_init`, `MYSQL_OPT_CONNECT_TIMEOUT`, `my_bool`, `mysql_real_connect`, `MYSQL_OPT_RECONNECT `, etc. ...

Am I missing something? Thanks!

**Comment by novi** [comment]
`UnsafeMutablePointer<MYSQL>` is used with C mysql header includes.
You would use this library via Package Manager and follow `Installation` of [README.md](https://github.com/novi/mysql-swift#installation).

**Comment by LinusGeffarth** [comment]
Ok, I've never used Package Manager, so I thought I might get around it 😄. Will try and report back. Thanks for the quick response!

**Comment by LinusGeffarth** [comment]
So I installed Swift Package Manager, `cd`'d into the project directory, ran `swift package init`, opened and modified the packages.swift file as described in the readme,  and ran `swift package resolve` (resolve is new for fetch). It says "fetching ..." and "cloning..." the urls. Then, I open the project (.xcworkspace, since I'm also using cocoapods) and try to import mysql-swift, but it doesn't know the module.

What am I doing wrong?

**Comment by novi** [comment]
Use `$ swift package generate-xcodeproj` for generating Xcode project of your app. Cocoapods or other package manager might be not working together.
Note that Swift Package Manager imports mysql-swift automatically. No need import that manually.
