### ISSUE TITLE
Support for inserting multiple rows in a single statement

### ISSUE THREAD

**Issue by florianreinhart** [novi/mysql-swift#62]
In node-mysql I can do something like this:

```swift
let users: [User] = [user1, user2, user3]
try connection.query("INSERT INTO User (id, name, age) VALUES ?", [users])
```

In mysql-swift I have to manually build the query string depending on the number of rows, e.g. `"INSERT INTO User (id, name, age) VALUES (?,?,?), (?,?,?), (?,?,?)"`.

I could also be missing something. Is there another way to achieve this in mysql-swift?

**Comment by novi** [comment]
We already have the way to do multiple inserting (or bulk inserting) like [this](https://github.com/novi/mysql-swift/commit/f9f955b971249ef39ff54f94f571515f00690d88#diff-284363ca631a1853ff95b3a8b4f6dea7).
But we have to convert models into `QueryArray` to do that.

**Comment by florianreinhart** [comment]
Thanks! That's better then my previous implementation.
