### ISSUE TITLE
connectionPoolGetConnectionError

### ISSUE THREAD

**Issue by shiwenwen** [novi/mysql-swift#67]
When the service runs for a period of time, it will be a mistake --- connectionPoolGetConnectionError

**Comment by HansOspina** [comment]
I use this one for 2 production apps
-One with high usage that has zero issues.
-One with very low usage(around every 2 or 3 days when the customer is testing) and this one breaks...it cannot get a connection from the pool, I have to restart the server.

**Comment by novi** [comment]
Thanks for reporting.
I investigate for that.

**Comment by PoissonBallon** [comment]
Any news about it ? I have the same issue :/

**Comment by novi** [comment]
Can you try to enable `reconnect` option in `ConnectionOption` ?

**Comment by novi** [comment]
In 0.9.0, `reconnect` option is enabled as defaults.
