### ISSUE TITLE
Batch inserts

### ISSUE THREAD

**Issue by awalkerr** [novi/mysql-swift#95]
How to bulk insert data?

**Comment by novi** [comment]
Insert your data with `QueryParameterArray`. See bulk insert [tests](https://github.com/novi/mysql-swift/blob/0b25e1763ae06aa4623c32716b5bdd920484ac0e/Tests/MySQLTests/QueryTests.swift#L210-L216).

**Comment by iwalkerr** [comment]
thank you!
